### ISSUE TITLE
KeyError: 'av_action_ids'

### ISSUE THREAD

**Issue by yuchen2199** [salmank255/Road-waymo-dataset#3]
File "ROAD++/ROAD_Waymo_Baseline-master/data/datasets.py", line 673, in _make_lists_road_waymo
    if len(frames[frame_id]['av_action_ids']) == 0:
KeyError: 'av_action_ids'

**Comment by salmank255** [comment]
Hi @yuchen2199

In the earlier version of our annotation file, we were not considering the av_actions that's why you are getting this error. 

Please download the updated annotation file from Community contributions section of Waymo Open Dataset following this link "https://waymo.com/open/download/"

**Comment by yuchen2199** [comment]
Are the earlier version of training videos exactly the same as the updated ones?

**Comment by salmank255** [comment]
Yes, they are exactly the same.
